//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.Горводоканал
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обращения.
    /// </summary>
    // *** Start programmer edit section *** (Обращения CustomAttributes)

    // *** End programmer edit section *** (Обращения CustomAttributes)
    [BusinessServer("Sneg.Горводоканал.ОбращенияBS, Горводоканал.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбращенияE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "ФИООбратившегося as \'ФИО обратившегося\' on \'-Обратившийся\'",
            "Адрес as \'Адрес\' on \'-Обратившийся\'",
            "Телефон as \'Телефон\' on \'-Обратившийся\'",
            "Тип as \'Тип\'",
            "Вид as \'Вид\'",
            "Причина as \'Причина\'",
            "Оператор as \'Оператор\'",
            "Ответственный as \'Ответственный\'"})]
    [MasterViewDefineAttribute("ОбращенияE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращенияE", "Вид", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращенияE", "Причина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращенияE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбращенияE", "Ответственный", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОбращенияL", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "Тип.Название as \'Тип\'",
            "Вид.Название as \'Вид\'",
            "Причина.Название as \'Причина\'"})]
    public class Обращения : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private Sneg.Горводоканал.tСтатусОбращения fСтатус;
        
        private System.DateTime? fДатаПоступления;
        
        private System.DateTime? fДатаЗакрытия;
        
        private string fФИООбратившегося;
        
        private string fАдрес;
        
        private string fТелефон;
        
        private Sneg.Горводоканал.Сотрудник fОператор;
        
        private Sneg.Горводоканал.ТипОбращения fТип;
        
        private Sneg.Горводоканал.ВидОбращения fВид;
        
        private Sneg.Горводоканал.Сотрудник fОтветственный;
        
        private Sneg.Горводоканал.ПричинаОбращения fПричина;
        
        // *** Start programmer edit section *** (Обращения CustomMembers)

        // *** End programmer edit section *** (Обращения CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Номер CustomAttributes)

        // *** End programmer edit section *** (Обращения.Номер CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Номер Get start)

                // *** End programmer edit section *** (Обращения.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Обращения.Номер Get end)

                // *** End programmer edit section *** (Обращения.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Номер Set start)

                // *** End programmer edit section *** (Обращения.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Обращения.Номер Set end)

                // *** End programmer edit section *** (Обращения.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Статус CustomAttributes)

        // *** End programmer edit section *** (Обращения.Статус CustomAttributes)
        public virtual Sneg.Горводоканал.tСтатусОбращения Статус
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Статус Get start)

                // *** End programmer edit section *** (Обращения.Статус Get start)
                Sneg.Горводоканал.tСтатусОбращения result = this.fСтатус;
                // *** Start programmer edit section *** (Обращения.Статус Get end)

                // *** End programmer edit section *** (Обращения.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Статус Set start)

                // *** End programmer edit section *** (Обращения.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Обращения.Статус Set end)

                // *** End programmer edit section *** (Обращения.Статус Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоступления.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.ДатаПоступления CustomAttributes)

        // *** End programmer edit section *** (Обращения.ДатаПоступления CustomAttributes)
        public virtual System.DateTime? ДатаПоступления
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.ДатаПоступления Get start)

                // *** End programmer edit section *** (Обращения.ДатаПоступления Get start)
                System.DateTime? result = this.fДатаПоступления;
                // *** Start programmer edit section *** (Обращения.ДатаПоступления Get end)

                // *** End programmer edit section *** (Обращения.ДатаПоступления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.ДатаПоступления Set start)

                // *** End programmer edit section *** (Обращения.ДатаПоступления Set start)
                this.fДатаПоступления = value;
                // *** Start programmer edit section *** (Обращения.ДатаПоступления Set end)

                // *** End programmer edit section *** (Обращения.ДатаПоступления Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗакрытия.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.ДатаЗакрытия CustomAttributes)

        // *** End programmer edit section *** (Обращения.ДатаЗакрытия CustomAttributes)
        public virtual System.DateTime? ДатаЗакрытия
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.ДатаЗакрытия Get start)

                // *** End programmer edit section *** (Обращения.ДатаЗакрытия Get start)
                System.DateTime? result = this.fДатаЗакрытия;
                // *** Start programmer edit section *** (Обращения.ДатаЗакрытия Get end)

                // *** End programmer edit section *** (Обращения.ДатаЗакрытия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.ДатаЗакрытия Set start)

                // *** End programmer edit section *** (Обращения.ДатаЗакрытия Set start)
                this.fДатаЗакрытия = value;
                // *** Start programmer edit section *** (Обращения.ДатаЗакрытия Set end)

                // *** End programmer edit section *** (Обращения.ДатаЗакрытия Set end)
            }
        }
        
        /// <summary>
        /// ФИООбратившегося.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.ФИООбратившегося CustomAttributes)

        // *** End programmer edit section *** (Обращения.ФИООбратившегося CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string ФИООбратившегося
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.ФИООбратившегося Get start)

                // *** End programmer edit section *** (Обращения.ФИООбратившегося Get start)
                string result = this.fФИООбратившегося;
                // *** Start programmer edit section *** (Обращения.ФИООбратившегося Get end)

                // *** End programmer edit section *** (Обращения.ФИООбратившегося Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.ФИООбратившегося Set start)

                // *** End programmer edit section *** (Обращения.ФИООбратившегося Set start)
                this.fФИООбратившегося = value;
                // *** Start programmer edit section *** (Обращения.ФИООбратившегося Set end)

                // *** End programmer edit section *** (Обращения.ФИООбратившегося Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Адрес CustomAttributes)

        // *** End programmer edit section *** (Обращения.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Адрес Get start)

                // *** End programmer edit section *** (Обращения.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Обращения.Адрес Get end)

                // *** End programmer edit section *** (Обращения.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Адрес Set start)

                // *** End programmer edit section *** (Обращения.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Обращения.Адрес Set end)

                // *** End programmer edit section *** (Обращения.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Телефон CustomAttributes)

        // *** End programmer edit section *** (Обращения.Телефон CustomAttributes)
        [StrLen(150)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Телефон Get start)

                // *** End programmer edit section *** (Обращения.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Обращения.Телефон Get end)

                // *** End programmer edit section *** (Обращения.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Телефон Set start)

                // *** End programmer edit section *** (Обращения.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Обращения.Телефон Set end)

                // *** End programmer edit section *** (Обращения.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Обращения.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Оператор CustomAttributes)

        // *** End programmer edit section *** (Обращения.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        public virtual Sneg.Горводоканал.Сотрудник Оператор
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Оператор Get start)

                // *** End programmer edit section *** (Обращения.Оператор Get start)
                Sneg.Горводоканал.Сотрудник result = this.fОператор;
                // *** Start programmer edit section *** (Обращения.Оператор Get end)

                // *** End programmer edit section *** (Обращения.Оператор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Оператор Set start)

                // *** End programmer edit section *** (Обращения.Оператор Set start)
                this.fОператор = value;
                // *** Start programmer edit section *** (Обращения.Оператор Set end)

                // *** End programmer edit section *** (Обращения.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Обращения.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Тип CustomAttributes)

        // *** End programmer edit section *** (Обращения.Тип CustomAttributes)
        [PropertyStorage(new string[] {
                "Тип"})]
        public virtual Sneg.Горводоканал.ТипОбращения Тип
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Тип Get start)

                // *** End programmer edit section *** (Обращения.Тип Get start)
                Sneg.Горводоканал.ТипОбращения result = this.fТип;
                // *** Start programmer edit section *** (Обращения.Тип Get end)

                // *** End programmer edit section *** (Обращения.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Тип Set start)

                // *** End programmer edit section *** (Обращения.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Обращения.Тип Set end)

                // *** End programmer edit section *** (Обращения.Тип Set end)
            }
        }
        
        /// <summary>
        /// Обращения.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Вид CustomAttributes)

        // *** End programmer edit section *** (Обращения.Вид CustomAttributes)
        [PropertyStorage(new string[] {
                "Вид"})]
        public virtual Sneg.Горводоканал.ВидОбращения Вид
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Вид Get start)

                // *** End programmer edit section *** (Обращения.Вид Get start)
                Sneg.Горводоканал.ВидОбращения result = this.fВид;
                // *** Start programmer edit section *** (Обращения.Вид Get end)

                // *** End programmer edit section *** (Обращения.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Вид Set start)

                // *** End programmer edit section *** (Обращения.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Обращения.Вид Set end)

                // *** End programmer edit section *** (Обращения.Вид Set end)
            }
        }
        
        /// <summary>
        /// Обращения.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Обращения.Ответственный CustomAttributes)
        [PropertyStorage(new string[] {
                "Ответственный"})]
        public virtual Sneg.Горводоканал.Сотрудник Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Ответственный Get start)

                // *** End programmer edit section *** (Обращения.Ответственный Get start)
                Sneg.Горводоканал.Сотрудник result = this.fОтветственный;
                // *** Start programmer edit section *** (Обращения.Ответственный Get end)

                // *** End programmer edit section *** (Обращения.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Ответственный Set start)

                // *** End programmer edit section *** (Обращения.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Обращения.Ответственный Set end)

                // *** End programmer edit section *** (Обращения.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Обращения.
        /// </summary>
        // *** Start programmer edit section *** (Обращения.Причина CustomAttributes)

        // *** End programmer edit section *** (Обращения.Причина CustomAttributes)
        [PropertyStorage(new string[] {
                "Причина"})]
        public virtual Sneg.Горводоканал.ПричинаОбращения Причина
        {
            get
            {
                // *** Start programmer edit section *** (Обращения.Причина Get start)

                // *** End programmer edit section *** (Обращения.Причина Get start)
                Sneg.Горводоканал.ПричинаОбращения result = this.fПричина;
                // *** Start programmer edit section *** (Обращения.Причина Get end)

                // *** End programmer edit section *** (Обращения.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращения.Причина Set start)

                // *** End programmer edit section *** (Обращения.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (Обращения.Причина Set end)

                // *** End programmer edit section *** (Обращения.Причина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбращенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращенияE", typeof(Sneg.Горводоканал.Обращения));
                }
            }
            
            /// <summary>
            /// "ОбращенияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращенияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращенияL", typeof(Sneg.Горводоканал.Обращения));
                }
            }
        }
    }
}
