//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using ICSSoft.STORMNET;
namespace Sneg.Горводоканал
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обращения BS.
    /// </summary>
    // *** Start programmer edit section *** (ОбращенияBS CustomAttributes)

    // *** End programmer edit section *** (ОбращенияBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОбращенияBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ОбращенияBS CustomMembers)

        // *** End programmer edit section *** (ОбращенияBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateОбращения CustomAttributes)

        // *** End programmer edit section *** (OnUpdateОбращения CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateОбращения(Sneg.Горводоканал.Обращения UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateОбращения)
            if(UpdatedObject.GetStatus() == ObjectStatus.Created)
            {
                UpdatedObject.ДатаПоступления = DateTime.Now;
            }

            if (UpdatedObject.GetStatus() == ObjectStatus.Altered && UpdatedObject.Статус == tСтатусОбращения.Закрыто)
            {
                UpdatedObject.ДатаЗакрытия = DateTime.Now;
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateОбращения)
        }
    }
}
