/*flexberryautogenerated="true"*/
namespace Sneg.Горводоканал
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ОбращенияL : BaseListForm<Обращения>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ОбращенияL() : base(Обращения.Views.ОбращенияL)
        {
            EditPage = ОбращенияE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Obrashheniya/ObrashheniyaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
