<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="ObrashheniyaE.aspx.cs" Inherits="Sneg.Горводоканал.ОбращенияE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Обращения</h2>
        <asp:ValidationSummary runat="server" ValidationGroup="savedoc" />
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlНомерLabel" runat="server" Text="Номер" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlНомер" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlНомерRequiredFieldValidator" runat="server" ControlToValidate="ctrlНомер"
                            ErrorMessage="Не указано: Номер" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСтатусLabel" runat="server" Text="Статус" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlСтатус" CssClass="descTxt" runat="server">
	<asp:ListItem>Открыто</asp:ListItem>
<asp:ListItem>НаКонтроле</asp:ListItem>
<asp:ListItem>ПрисоединеноКЗаявке</asp:ListItem>
<asp:ListItem>Закрыто</asp:ListItem>

</asp:DropDownList>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаПоступленияLabel" runat="server" Text="Дата поступления" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаПоступления" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДатаПоступленияDatePickerValidator" runat="server" ControlToValidate="ctrlДатаПоступления" 
                        ErrorMessage="Введена некорректная дата: Дата поступления." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаЗакрытияLabel" runat="server" Text="Дата закрытия" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаЗакрытия" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДатаЗакрытияDatePickerValidator" runat="server" ControlToValidate="ctrlДатаЗакрытия" 
                        ErrorMessage="Введена некорректная дата: Дата закрытия." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlТипLabel" runat="server" Text="Тип" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlТип" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlВидLabel" runat="server" Text="Вид" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlВид" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlПричинаLabel" runat="server" Text="Причина" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlПричина" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОператорLabel" runat="server" Text="Оператор" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlОператор" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОтветственныйLabel" runat="server" Text="Ответственный" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlОтветственный" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />


</div>
<br/>
<fieldset ID="ctrl_fsОбратившийся" style="clear: left">
	<legend>Обратившийся</legend>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlФИООбратившегосяLabel" runat="server" Text="ФИО обратившегося" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlФИООбратившегося" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlФИООбратившегосяRequiredFieldValidator" runat="server" ControlToValidate="ctrlФИООбратившегося"
                            ErrorMessage="Не указано: ФИООбратившегося" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАдресLabel" runat="server" Text="Адрес" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlАдрес" runat="server">
</asp:TextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlТелефонLabel" runat="server" Text="Телефон" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlТелефон" runat="server">
</asp:TextBox>


</div>

</fieldset>
</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
